### ISSUE TITLE
update staged.dependencies as Nik suggested

### ISSUE THREAD

**Issue by shajoezhu** [Roche/rtables#296]
```
downstream_repos:
  insightsengineering/tern:
    repo: insightsengineering/tern
    host: https://github.com
  insightsengineering/teal.osprey:
    repo: insightsengineering/teal.osprey
    host: https://github.com
  <<others here>>

```
